# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 01a950949fc690919b99ad697c79306014bd044db2800481cb5ef42cd8764eaa19b9cfe49ae66b05d01246e1e01385f314522cee1451a18389b0ef3446451d4e

test:
  secret_key_base: f06064d044b62d28f9458bd55d09f95af44b125816fe69239edc6d2f2f5f525b06b4ba0d3e22e2a82659a41853950e9b3ed8058013c8ca11de0147b443657885

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  bucket: <%= ['S3_BUCKET_NAME'] %>
  access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
