# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 131b68dc9c2b981efc098bd35b418c1ba43dc0457305273448fb8d68d399c9063ac749e73bd31e6ba12576ed405bf4a9557b2439db4f630874173ed2d203ea9a

test:
  secret_key_base: 2d33b9c1c3bc929cfbef7fbb7c1aedabc9d44e1cf5c384bacb90c6c691eb767157c22a2224cdebb2ccaa825019d87816c3edd7f1679ec776f179b39b225d1ae5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
